services:
  
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Aa123456
      MYSQL_DATABASE: Yetinder_Lesak_DB

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080