services:
  
  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: Aa123456
      MARIADB_DATABASE: Yetinder_Lesak_DB

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080